-- ============================================================
-- Synthetic Data : stg_employees
-- Generated at  : 2026-04-23 15:35:37 UTC
-- Records       : 100
-- Date range    : 2026-04-08 → 2026-04-23
-- Source mapping: model_SCRUM-5_20260422_18_mapping
-- Target table  : `verizon-data.deah_pod.stg_employees`
-- Partition by  : hire_date
-- Cluster by    : job_id, department_id, status
-- Generated by  : Claude Agent (pure-python)
-- ============================================================

-- Column reference:
--   employee_id                    INT64          
--   first_name                     STRING         
--   last_name                      STRING         
--   email                          STRING         
--   phone_number                   STRING         
--   hire_date                      DATE            [PARTITION]
--   job_id                         STRING          [CLUSTER]
--   salary                         NUMERIC        
--   commission_pct                 NUMERIC        
--   manager_id                     INT64          
--   department_id                  INT64           [CLUSTER]
--   status                         STRING          [CLUSTER]
--   created_date                   TIMESTAMP      
--   updated_date                   TIMESTAMP      

INSERT INTO `verizon-data.deah_pod.stg_employees`
  (`employee_id`, `first_name`, `last_name`, `email`, `phone_number`, `hire_date`, `job_id`, `salary`, `commission_pct`, `manager_id`, `department_id`, `status`, `created_date`, `updated_date`)
VALUES
  (1000, 'Patricia', 'Smith', 'charles.thompson@solutions.org', '+1-502-628-7390', DATE('2026-04-13'), 'AD_PRES', 200231.51, 0.08, 3968, 78773, 'suspended', TIMESTAMP('2026-04-09 08:47:41'), TIMESTAMP('2026-04-12 05:10:20')),
  (1001, 'Lisa', 'Hernandez', 'liam.fischer@corp.org', '+1-852-268-7079', DATE('2026-04-19'), 'MK_REP', 154093.43, 0.05, NULL, 19361, 'suspended', TIMESTAMP('2026-04-17 10:15:56'), TIMESTAMP('2026-04-11 23:14:15')),
  (1002, 'Wei', 'Tanaka', 'sarah.brown@dataworks.net', '+1-216-274-5610', DATE('2026-04-21'), 'PU_CLERK', 142761.56, 0.22, 9711, 61227, 'on_leave', TIMESTAMP('2026-04-14 18:24:21'), TIMESTAMP('2026-04-09 02:41:19')),
  (1003, 'Emma', 'Moore', 'priya.singh@enterprise.net', '+1-867-468-5391', DATE('2026-04-15'), 'HR_MAN', 184352.95, 0.14, 5900, 46147, 'active', TIMESTAMP('2026-04-18 20:06:02'), TIMESTAMP('2026-04-09 18:36:15')),
  (1004, 'Ivan', 'Chen', 'oliver.kumar@acme.com', '+1-808-980-7932', DATE('2026-04-21'), 'IT_MAN', 42934.9, 0.29, 8261, 97797, 'pending', TIMESTAMP('2026-04-20 23:44:10'), TIMESTAMP('2026-04-10 02:09:54')),
  (1005, 'Carlos', 'Martinez', 'isabella.brown@acme.com', '+1-915-571-4649', DATE('2026-04-13'), 'ST_CLERK', 42211.73, 0.24, 6727, 62995, 'suspended', TIMESTAMP('2026-04-08 01:32:32'), TIMESTAMP('2026-04-22 03:08:15')),
  (1006, 'Richard', 'Anderson', 'david.rodriguez@corp.org', '+1-982-250-7557', DATE('2026-04-11'), 'AD_VP', 188671.41, NULL, 1267, 39034, 'on_leave', TIMESTAMP('2026-04-10 00:45:02'), TIMESTAMP('2026-04-09 15:38:45')),
  (1007, 'Lisa', 'Miller', 'emma.sato@acme.com', '+1-262-152-2734', DATE('2026-04-16'), 'ST_MAN', 151988.68, 0.35, 4891, 31429, 'inactive', TIMESTAMP('2026-04-13 03:19:55'), TIMESTAMP('2026-04-12 11:07:01')),
  (1008, 'Oliver', 'Brown', 'ivan.silva@business.io', '+1-738-114-9231', DATE('2026-04-12'), 'HR_REP', 72198.16, 0.39, 3205, 32326, 'on_leave', TIMESTAMP('2026-04-10 19:39:38'), TIMESTAMP('2026-04-11 01:12:23')),
  (1009, 'Barbara', 'Nkosi', 'amara.nguyen@acme.com', '+1-754-427-2768', DATE('2026-04-15'), 'IT_MAN', 238842.7, 0.03, 8554, 44728, 'terminated', TIMESTAMP('2026-04-20 17:59:43'), TIMESTAMP('2026-04-17 23:28:45')),
  (1010, 'Kenji', 'Martin', 'mary.anderson@globaltech.com', '+1-772-792-4740', DATE('2026-04-11'), 'MK_MAN', 41253.5, 0.26, 9799, 45419, 'active', TIMESTAMP('2026-04-21 06:26:42'), TIMESTAMP('2026-04-10 08:18:09')),
  (1011, 'James', 'Brown', 'jennifer.ferreira@corp.org', '+1-562-295-3271', DATE('2026-04-19'), 'MK_MAN', 96225.2, 0.38, 3131, 43574, 'terminated', TIMESTAMP('2026-04-13 23:01:54'), TIMESTAMP('2026-04-14 09:04:53')),
  (1012, 'David', 'Okafor', 'yuki.ferreira@globaltech.com', '+1-844-564-9611', DATE('2026-04-21'), 'MK_REP', 66880.47, NULL, 7646, 44496, 'pending', TIMESTAMP('2026-04-11 13:03:27'), TIMESTAMP('2026-04-10 05:12:58')),
  (1013, 'Priya', 'Brown', 'sophia.martin@company.com', '+1-992-490-2107', DATE('2026-04-14'), 'PU_MAN', 37172.9, 0.13, 3215, 47442, 'pending', TIMESTAMP('2026-04-19 23:44:22'), TIMESTAMP('2026-04-21 08:27:42')),
  (1014, 'Natasha', 'Ferreira', 'robert.singh@corp.org', '+1-447-177-2621', DATE('2026-04-15'), 'HR_MAN', 111288.18, 0.25, 5160, 60076, 'terminated', TIMESTAMP('2026-04-13 17:45:43'), TIMESTAMP('2026-04-08 17:50:52')),
  (1015, 'Fatima', 'Brown', 'thomas.sato@business.io', '+1-633-506-7725', DATE('2026-04-15'), 'SH_CLERK', 185710.53, 0.37, 2961, 19454, 'suspended', TIMESTAMP('2026-04-09 06:01:01'), TIMESTAMP('2026-04-21 15:10:30')),
  (1016, 'Mohamed', 'Hernandez', 'mohamed.rodriguez@enterprise.net', '+1-314-112-3026', DATE('2026-04-13'), 'FI_MGR', 39959.77, 0.12, NULL, 75558, 'active', TIMESTAMP('2026-04-10 19:51:29'), TIMESTAMP('2026-04-21 20:48:02')),
  (1017, 'Lisa', 'Nkosi', 'fatima.fischer@acme.com', '+1-990-214-8401', DATE('2026-04-12'), 'ST_MAN', 128044.76, NULL, NULL, 11242, 'active', TIMESTAMP('2026-04-20 01:28:31'), TIMESTAMP('2026-04-21 10:45:55')),
  (1018, 'Chen', 'Ferreira', 'richard.smith@enterprise.net', '+1-345-657-1821', DATE('2026-04-10'), 'MK_REP', 89278.62, 0.24, NULL, 56384, 'active', TIMESTAMP('2026-04-19 14:18:40'), TIMESTAMP('2026-04-23 21:35:29')),
  (1019, 'David', 'Jones', 'ali.wang@business.io', '+1-311-878-6312', DATE('2026-04-20'), 'FI_MGR', 134472.2, 0.09, 7759, 88618, 'inactive', TIMESTAMP('2026-04-16 08:46:48'), TIMESTAMP('2026-04-12 16:50:17')),
  (1020, 'Susan', 'Miller', 'robert.taylor@enterprise.net', '+1-583-496-2005', DATE('2026-04-12'), 'ST_CLERK', 140104.97, 0.24, 9816, 19515, 'pending', TIMESTAMP('2026-04-12 02:39:12'), TIMESTAMP('2026-04-10 11:50:44')),
  (1021, 'Sophia', 'Silva', 'thomas.wang@globaltech.com', '+1-489-203-4536', DATE('2026-04-10'), 'IT_MAN', 193297.76, NULL, 7859, 39669, 'active', TIMESTAMP('2026-04-22 09:00:50'), TIMESTAMP('2026-04-10 11:57:22')),
  (1022, 'Mateus', 'Thompson', 'patricia.garcia@enterprise.net', '+1-302-346-6343', DATE('2026-04-11'), 'FI_ACCOUNT', 200185.85, 0.2, 8723, 45505, 'on_leave', TIMESTAMP('2026-04-23 16:40:57'), TIMESTAMP('2026-04-10 08:10:09')),
  (1023, 'Ana', 'Brown', 'aisha.wilson@globaltech.com', '+1-281-804-4686', DATE('2026-04-19'), 'MK_MAN', 85267.01, NULL, NULL, 60419, 'inactive', TIMESTAMP('2026-04-11 07:14:28'), TIMESTAMP('2026-04-21 13:48:58')),
  (1024, 'Jennifer', 'Rodriguez', 'elena.rodriguez@business.io', '+1-340-573-7952', DATE('2026-04-12'), 'IT_PROG', 118837.83, 0.31, 4286, 94531, 'active', TIMESTAMP('2026-04-21 01:10:08'), TIMESTAMP('2026-04-11 19:59:26')),
  (1025, 'Joseph', 'Hernandez', 'patricia.patel@enterprise.net', '+1-399-587-7969', DATE('2026-04-22'), 'PU_CLERK', 111608.0, 0.14, 9464, 1807, 'pending', TIMESTAMP('2026-04-21 01:09:52'), TIMESTAMP('2026-04-21 04:03:35')),
  (1026, 'Sofia', 'Smith', 'jessica.silva@company.com', '+1-385-774-2048', DATE('2026-04-20'), 'ST_CLERK', 126189.37, 0.26, 7286, 41067, 'terminated', TIMESTAMP('2026-04-08 21:38:05'), TIMESTAMP('2026-04-23 20:10:46')),
  (1027, 'William', 'Nkosi', 'aisha.okafor@business.io', '+1-868-977-7535', DATE('2026-04-20'), 'PU_CLERK', 111448.84, 0.29, 9484, 97575, 'pending', TIMESTAMP('2026-04-08 16:59:04'), TIMESTAMP('2026-04-10 02:52:18')),
  (1028, 'Rahul', 'Rodriguez', 'mateus.smith@solutions.org', '+1-577-441-6723', DATE('2026-04-08'), 'FI_ACCOUNT', 193483.76, 0.33, 9480, 46354, 'on_leave', TIMESTAMP('2026-04-15 10:55:11'), TIMESTAMP('2026-04-08 09:40:13')),
  (1029, 'Oliver', 'Garcia', 'rahul.silva@enterprise.net', '+1-371-969-6528', DATE('2026-04-20'), 'PU_MAN', 233718.34, 0.02, 5739, 94402, 'terminated', TIMESTAMP('2026-04-10 23:07:28'), TIMESTAMP('2026-04-14 17:15:50')),
  (1030, 'Robert', 'Sato', 'sarah.fischer@acme.com', '+1-456-755-3024', DATE('2026-04-21'), 'AD_VP', 58134.41, 0.02, 2525, 61693, 'active', TIMESTAMP('2026-04-11 03:14:21'), TIMESTAMP('2026-04-21 08:36:24')),
  (1031, 'Richard', 'Williams', 'aisha.singh@enterprise.net', '+1-622-916-1240', DATE('2026-04-08'), 'SA_MAN', 171036.46, 0.38, 2982, 32459, 'terminated', TIMESTAMP('2026-04-11 04:59:17'), TIMESTAMP('2026-04-14 20:22:16')),
  (1032, 'Priya', 'Mensah', 'natasha.patel@company.com', '+1-494-563-7017', DATE('2026-04-16'), 'FI_ACCOUNT', 236639.64, 0.05, 8703, 62908, 'suspended', TIMESTAMP('2026-04-22 09:08:02'), TIMESTAMP('2026-04-21 02:54:03')),
  (1033, 'Linda', 'Martin', 'ana.davis@solutions.org', '+1-958-609-9886', DATE('2026-04-12'), 'PU_MAN', 64028.27, NULL, 1568, 70279, 'on_leave', TIMESTAMP('2026-04-20 13:30:32'), TIMESTAMP('2026-04-23 02:59:48')),
  (1034, 'Kofi', 'Rodriguez', 'ana.chen@business.io', '+1-465-297-1343', DATE('2026-04-16'), 'AD_PRES', 64977.21, 0.03, 3690, 27042, 'pending', TIMESTAMP('2026-04-13 23:19:22'), TIMESTAMP('2026-04-23 08:33:02')),
  (1035, 'Sophia', 'Ferreira', 'thomas.khan@globaltech.com', '+1-272-516-7690', DATE('2026-04-10'), 'PU_CLERK', 184026.09, 0.36, 9058, 93673, 'terminated', TIMESTAMP('2026-04-08 10:15:54'), TIMESTAMP('2026-04-18 20:55:53')),
  (1036, 'Sophia', 'Brown', 'ivan.diallo@business.io', '+1-576-921-9420', DATE('2026-04-20'), 'FI_MGR', 154443.89, 0.16, 8875, 65012, 'pending', TIMESTAMP('2026-04-11 22:59:18'), TIMESTAMP('2026-04-13 19:24:45')),
  (1037, 'Noah', 'Mueller', 'william.taylor@corp.org', '+1-272-442-6898', DATE('2026-04-13'), 'MK_MAN', 51439.13, 0.11, 1187, 53789, 'active', TIMESTAMP('2026-04-08 14:13:26'), TIMESTAMP('2026-04-17 02:11:47')),
  (1038, 'Elena', 'Brown', 'yuki.jones@business.io', '+1-611-842-9937', DATE('2026-04-20'), 'AD_VP', 49710.06, 0.04, 5852, 87630, 'on_leave', TIMESTAMP('2026-04-14 15:09:51'), TIMESTAMP('2026-04-10 23:40:41')),
  (1039, 'Yuki', 'Sato', 'barbara.chen@dataworks.net', '+1-662-759-3113', DATE('2026-04-09'), 'ST_CLERK', 48775.18, 0.25, 1564, 69375, 'active', TIMESTAMP('2026-04-11 19:10:25'), TIMESTAMP('2026-04-09 16:03:14')),
  (1040, 'Kenji', 'Brown', 'natasha.silva@company.com', '+1-760-296-3074', DATE('2026-04-22'), 'MK_REP', 151698.44, 0.37, 8477, 83226, 'terminated', TIMESTAMP('2026-04-16 11:18:12'), TIMESTAMP('2026-04-16 05:39:11')),
  (1041, 'Richard', 'Thomas', 'charles.schmidt@business.io', '+1-899-645-1701', DATE('2026-04-21'), 'MK_MAN', 79818.11, 0.38, 5957, 52610, 'inactive', TIMESTAMP('2026-04-11 17:37:05'), TIMESTAMP('2026-04-14 01:16:15')),
  (1042, 'Oliver', 'Jones', 'kofi.wang@company.com', '+1-346-153-3156', DATE('2026-04-22'), 'HR_MAN', 248240.16, 0.32, 3484, 85212, 'suspended', TIMESTAMP('2026-04-22 01:55:42'), TIMESTAMP('2026-04-15 14:29:20')),
  (1043, 'Ali', 'Ferreira', 'charles.johnson@acme.com', '+1-335-784-3554', DATE('2026-04-12'), 'AD_VP', 208506.27, 0.21, 6799, 49526, 'inactive', TIMESTAMP('2026-04-15 10:16:13'), TIMESTAMP('2026-04-16 18:10:29')),
  (1044, 'Carlos', 'Moore', 'jessica.wilson@solutions.org', '+1-484-196-3740', DATE('2026-04-21'), 'PU_MAN', 122786.18, 0.4, 6100, 55036, 'pending', TIMESTAMP('2026-04-23 01:09:55'), TIMESTAMP('2026-04-18 10:22:30')),
  (1045, 'Barbara', 'Nkosi', 'patricia.johnson@business.io', '+1-658-473-9131', DATE('2026-04-19'), 'AD_ASST', 120796.55, 0.05, 2921, 53705, 'suspended', TIMESTAMP('2026-04-14 05:21:08'), TIMESTAMP('2026-04-13 13:18:03')),
  (1046, 'John', 'Silva', 'kenji.oliveira@company.com', '+1-481-948-7362', DATE('2026-04-18'), 'SA_REP', 84482.41, 0.13, 4577, 93482, 'pending', TIMESTAMP('2026-04-16 17:07:58'), TIMESTAMP('2026-04-16 22:21:48')),
  (1047, 'Kofi', 'Chen', 'thomas.tanaka@company.com', '+1-359-145-4326', DATE('2026-04-09'), 'SA_MAN', 148620.19, 0.11, 7425, 39285, 'terminated', TIMESTAMP('2026-04-14 14:48:48'), TIMESTAMP('2026-04-20 15:10:04')),
  (1048, 'Yuki', 'Kim', 'robert.thomas@dataworks.net', '+1-831-955-7824', DATE('2026-04-19'), 'HR_MAN', 218791.64, 0.28, 2095, 85304, 'suspended', TIMESTAMP('2026-04-14 03:10:25'), TIMESTAMP('2026-04-22 15:46:43')),
  (1049, 'Linda', 'Thomas', 'james.kumar@solutions.org', '+1-594-401-3724', DATE('2026-04-22'), 'FI_ACCOUNT', 63209.38, 0.09, 6355, 13845, 'on_leave', TIMESTAMP('2026-04-10 19:22:48'), TIMESTAMP('2026-04-13 01:34:42')),
  (1050, 'Sophia', 'Sato', 'ali.tanaka@acme.com', '+1-415-544-9670', DATE('2026-04-19'), 'HR_REP', 169909.64, 0.2, 6940, 6358, 'inactive', TIMESTAMP('2026-04-13 08:30:19'), TIMESTAMP('2026-04-12 06:19:45')),
  (1051, 'Chen', 'Smith', 'jennifer.schmidt@dataworks.net', '+1-982-638-3018', DATE('2026-04-10'), 'MK_REP', 155163.54, 0.3, 9972, 12144, 'on_leave', TIMESTAMP('2026-04-19 13:10:17'), TIMESTAMP('2026-04-17 00:31:34')),
  (1052, 'Thomas', 'Jackson', 'liam.hernandez@dataworks.net', '+1-681-382-6709', DATE('2026-04-12'), 'ST_CLERK', 185183.94, NULL, 3966, 21489, 'terminated', TIMESTAMP('2026-04-12 06:04:21'), TIMESTAMP('2026-04-15 09:00:59')),
  (1053, 'Noah', 'Smith', 'emma.miller@enterprise.net', '+1-953-710-2486', DATE('2026-04-16'), 'PU_MAN', 222005.12, 0.32, 2850, 53313, 'terminated', TIMESTAMP('2026-04-12 01:19:57'), TIMESTAMP('2026-04-11 05:22:08')),
  (1054, 'Chen', 'Chen', 'sophia.garcia@solutions.org', '+1-317-906-6790', DATE('2026-04-21'), 'SA_MAN', 155415.11, 0.25, 9700, 48981, 'on_leave', TIMESTAMP('2026-04-16 15:12:36'), TIMESTAMP('2026-04-08 00:35:57')),
  (1055, 'Sarah', 'Moore', 'isabella.silva@solutions.org', '+1-389-806-2194', DATE('2026-04-11'), 'IT_MAN', 60331.74, 0.18, 4435, 68010, 'suspended', TIMESTAMP('2026-04-13 09:31:24'), TIMESTAMP('2026-04-11 15:45:24')),
  (1056, 'Liam', 'Moore', 'ivan.nkosi@acme.com', '+1-278-681-1450', DATE('2026-04-18'), 'ST_MAN', 59552.92, 0.27, 3671, 43482, 'suspended', TIMESTAMP('2026-04-21 12:28:20'), TIMESTAMP('2026-04-20 08:30:29')),
  (1057, 'Carlos', 'Diallo', 'oliver.jones@corp.org', '+1-509-200-6687', DATE('2026-04-09'), 'SA_MAN', 44115.21, 0.1, 7932, 76762, 'on_leave', TIMESTAMP('2026-04-19 00:59:52'), TIMESTAMP('2026-04-09 23:27:29')),
  (1058, 'Ali', 'Santos', 'ravi.santos@solutions.org', '+1-941-927-2073', DATE('2026-04-08'), 'AD_VP', 54405.36, 0.26, 9005, 46920, 'terminated', TIMESTAMP('2026-04-12 22:59:16'), TIMESTAMP('2026-04-10 19:08:32')),
  (1059, 'Ali', 'Williams', 'james.oliveira@acme.com', '+1-907-690-4462', DATE('2026-04-15'), 'ST_MAN', 170388.7, 0.15, 8741, 56241, 'active', TIMESTAMP('2026-04-12 20:03:12'), TIMESTAMP('2026-04-17 03:03:58')),
  (1060, 'Isabella', 'Wang', 'liam.nkosi@company.com', '+1-884-744-5161', DATE('2026-04-21'), 'PU_MAN', 123767.71, NULL, 7553, 53071, 'active', TIMESTAMP('2026-04-23 22:31:05'), TIMESTAMP('2026-04-12 08:04:27')),
  (1061, 'Mary', 'Mueller', 'jessica.anderson@dataworks.net', '+1-732-175-1406', DATE('2026-04-18'), 'MK_MAN', 31630.65, 0.35, 6996, 83047, 'inactive', TIMESTAMP('2026-04-10 07:05:09'), TIMESTAMP('2026-04-16 05:31:22')),
  (1062, 'Linda', 'Wang', 'jessica.davis@dataworks.net', '+1-702-778-9864', DATE('2026-04-13'), 'PU_MAN', 69064.83, NULL, NULL, 53605, 'on_leave', TIMESTAMP('2026-04-17 14:08:02'), TIMESTAMP('2026-04-16 07:09:01')),
  (1063, 'Chen', 'Ferreira', 'aisha.ferreira@globaltech.com', '+1-465-842-7422', DATE('2026-04-12'), 'FI_ACCOUNT', 177053.83, 0.06, 7167, 87178, 'on_leave', TIMESTAMP('2026-04-12 14:03:04'), TIMESTAMP('2026-04-23 15:25:15')),
  (1064, 'Yuki', 'Mensah', 'emma.santos@enterprise.net', '+1-798-268-6429', DATE('2026-04-10'), 'SA_REP', 32060.36, NULL, 5084, 76289, 'terminated', TIMESTAMP('2026-04-08 18:43:06'), TIMESTAMP('2026-04-12 01:21:21')),
  (1065, 'Michael', 'Wilson', 'kenji.mueller@solutions.org', '+1-981-485-2417', DATE('2026-04-15'), 'HR_REP', 173715.05, 0.33, 5090, 90381, 'active', TIMESTAMP('2026-04-21 04:46:52'), TIMESTAMP('2026-04-20 12:14:39')),
  (1066, 'Mary', 'Ferreira', 'william.rodriguez@business.io', '+1-663-787-7873', DATE('2026-04-09'), 'SH_CLERK', 218555.35, 0.07, 2822, 56985, 'on_leave', TIMESTAMP('2026-04-08 11:36:42'), TIMESTAMP('2026-04-21 02:25:54')),
  (1067, 'Isabella', 'Kim', 'susan.ferreira@solutions.org', '+1-393-181-1598', DATE('2026-04-15'), 'SH_CLERK', 138926.19, NULL, 8219, 90725, 'active', TIMESTAMP('2026-04-22 12:15:25'), TIMESTAMP('2026-04-15 02:15:12')),
  (1068, 'Jessica', 'Okafor', 'ivan.thomas@business.io', '+1-872-112-6604', DATE('2026-04-20'), 'SA_MAN', 69112.9, 0.22, 8997, 48199, 'terminated', TIMESTAMP('2026-04-10 16:09:32'), TIMESTAMP('2026-04-10 12:32:07')),
  (1069, 'Oliver', 'Thompson', 'linda.singh@solutions.org', '+1-431-338-1101', DATE('2026-04-14'), 'AD_ASST', 207129.36, 0.1, NULL, 7199, 'pending', TIMESTAMP('2026-04-21 09:12:19'), TIMESTAMP('2026-04-16 21:01:15')),
  (1070, 'Joseph', 'Wang', 'carlos.fischer@company.com', '+1-655-572-8217', DATE('2026-04-15'), 'FI_MGR', 60266.31, 0.06, 6364, 35214, 'suspended', TIMESTAMP('2026-04-23 07:39:41'), TIMESTAMP('2026-04-15 11:41:48')),
  (1071, 'Patricia', 'Kumar', 'susan.thomas@corp.org', '+1-521-238-1857', DATE('2026-04-14'), 'FI_MGR', 184351.06, 0.07, 1509, 95635, 'on_leave', TIMESTAMP('2026-04-20 04:00:45'), TIMESTAMP('2026-04-20 17:58:57')),
  (1072, 'Chen', 'Nguyen', 'james.williams@company.com', '+1-307-670-2869', DATE('2026-04-08'), 'SA_MAN', 114911.76, 0.08, 9692, 19889, 'terminated', TIMESTAMP('2026-04-23 19:29:10'), TIMESTAMP('2026-04-08 12:05:45')),
  (1073, 'Rahul', 'Singh', 'emma.chen@dataworks.net', '+1-455-534-3102', DATE('2026-04-16'), 'ST_MAN', 133748.69, NULL, NULL, 56209, 'on_leave', TIMESTAMP('2026-04-23 08:30:40'), TIMESTAMP('2026-04-18 04:54:34')),
  (1074, 'Ana', 'Williams', 'mateus.silva@globaltech.com', '+1-570-510-7573', DATE('2026-04-15'), 'PU_CLERK', 67714.03, 0.29, 3116, 95900, 'terminated', TIMESTAMP('2026-04-10 13:04:37'), TIMESTAMP('2026-04-12 11:06:35')),
  (1075, 'Wei', 'Singh', 'wei.martinez@dataworks.net', '+1-952-143-6153', DATE('2026-04-13'), 'AD_ASST', 47703.83, 0.05, 1862, 73068, 'on_leave', TIMESTAMP('2026-04-15 08:43:10'), TIMESTAMP('2026-04-08 21:22:34')),
  (1076, 'Lisa', 'Nguyen', 'rahul.silva@corp.org', '+1-945-471-3020', DATE('2026-04-18'), 'PU_CLERK', 38678.74, 0.37, NULL, 15084, 'suspended', TIMESTAMP('2026-04-16 08:23:36'), TIMESTAMP('2026-04-15 02:14:29')),
  (1077, 'Linda', 'Kumar', 'joseph.white@acme.com', '+1-779-627-8792', DATE('2026-04-22'), 'PU_CLERK', 114607.59, NULL, 6504, 70187, 'inactive', TIMESTAMP('2026-04-13 00:40:37'), TIMESTAMP('2026-04-08 02:17:29')),
  (1078, 'Mary', 'Ferreira', 'emma.mueller@corp.org', '+1-283-760-6529', DATE('2026-04-10'), 'FI_MGR', 50065.38, NULL, 9167, 96539, 'active', TIMESTAMP('2026-04-14 22:22:34'), TIMESTAMP('2026-04-08 09:13:11')),
  (1079, 'Fatima', 'Sato', 'linda.mensah@business.io', '+1-486-740-4036', DATE('2026-04-15'), 'FI_MGR', 42659.62, 0.1, 9078, 94610, 'terminated', TIMESTAMP('2026-04-17 21:11:51'), TIMESTAMP('2026-04-22 17:13:12')),
  (1080, 'Sofia', 'Jones', 'jessica.brown@company.com', '+1-684-511-8933', DATE('2026-04-13'), 'ST_MAN', 237821.4, 0.38, 3558, 35067, 'on_leave', TIMESTAMP('2026-04-08 17:53:11'), TIMESTAMP('2026-04-21 04:18:38')),
  (1081, 'Mary', 'Nkosi', 'kofi.jones@corp.org', '+1-436-293-6890', DATE('2026-04-17'), 'HR_REP', 226283.61, NULL, NULL, 38303, 'inactive', TIMESTAMP('2026-04-11 08:29:06'), TIMESTAMP('2026-04-14 06:03:09')),
  (1082, 'Wei', 'Khan', 'ravi.moore@corp.org', '+1-549-252-1275', DATE('2026-04-19'), 'AD_ASST', 48684.23, 0.26, 5280, 2705, 'on_leave', TIMESTAMP('2026-04-15 22:33:23'), TIMESTAMP('2026-04-20 19:42:48')),
  (1083, 'Priya', 'Nkosi', 'carlos.wang@company.com', '+1-938-916-1328', DATE('2026-04-22'), 'SH_CLERK', 111573.25, 0.15, 9409, 56742, 'inactive', TIMESTAMP('2026-04-19 14:22:07'), TIMESTAMP('2026-04-22 09:17:35')),
  (1084, 'Ivan', 'Kumar', 'mateus.johnson@dataworks.net', '+1-873-570-2630', DATE('2026-04-17'), 'HR_MAN', 206403.26, 0.29, 4585, 94051, 'terminated', TIMESTAMP('2026-04-21 11:37:52'), TIMESTAMP('2026-04-18 23:15:18')),
  (1085, 'Jessica', 'Thomas', 'ivan.khan@acme.com', '+1-671-600-2213', DATE('2026-04-12'), 'IT_PROG', 33425.01, 0.22, 6807, 33427, 'pending', TIMESTAMP('2026-04-14 03:03:10'), TIMESTAMP('2026-04-15 18:33:29')),
  (1086, 'Liam', 'Santos', 'joseph.smith@company.com', '+1-929-276-5253', DATE('2026-04-10'), 'MK_MAN', 66276.61, 0.01, 9191, 15018, 'suspended', TIMESTAMP('2026-04-18 04:27:28'), TIMESTAMP('2026-04-16 00:05:14')),
  (1087, 'Jessica', 'Santos', 'barbara.jackson@enterprise.net', '+1-592-718-4498', DATE('2026-04-20'), 'HR_REP', 179286.97, 0.14, 1167, 68754, 'active', TIMESTAMP('2026-04-17 05:28:06'), TIMESTAMP('2026-04-13 13:31:49')),
  (1088, 'Joseph', 'Smith', 'wei.jackson@dataworks.net', '+1-622-568-5355', DATE('2026-04-18'), 'AD_VP', 219604.79, 0.28, 2973, 55981, 'terminated', TIMESTAMP('2026-04-16 16:34:53'), TIMESTAMP('2026-04-23 06:55:54')),
  (1089, 'Ravi', 'Moore', 'michael.schmidt@corp.org', '+1-861-235-4355', DATE('2026-04-18'), 'ST_CLERK', 81765.55, 0.01, 5167, 41639, 'suspended', TIMESTAMP('2026-04-22 03:30:21'), TIMESTAMP('2026-04-08 21:51:57')),
  (1090, 'Priya', 'Kumar', 'elena.garcia@dataworks.net', '+1-678-830-3785', DATE('2026-04-12'), 'AD_ASST', 45912.35, 0.1, 8965, 50106, 'suspended', TIMESTAMP('2026-04-19 23:01:29'), TIMESTAMP('2026-04-20 13:39:20')),
  (1091, 'Michael', 'Wilson', 'ana.rodriguez@globaltech.com', '+1-386-137-6772', DATE('2026-04-20'), 'SH_CLERK', 238356.85, 0.2, 9991, 21932, 'active', TIMESTAMP('2026-04-11 16:55:09'), TIMESTAMP('2026-04-10 10:36:32')),
  (1092, 'Ivan', 'Moore', 'emma.thompson@dataworks.net', '+1-719-953-1425', DATE('2026-04-19'), 'PU_MAN', 83698.6, 0.38, 9994, 52532, 'suspended', TIMESTAMP('2026-04-09 20:35:03'), TIMESTAMP('2026-04-20 05:38:11')),
  (1093, 'Richard', 'Martin', 'ali.park@globaltech.com', '+1-894-749-4186', DATE('2026-04-12'), 'IT_PROG', 130438.84, 0.22, 1849, 69368, 'inactive', TIMESTAMP('2026-04-15 03:55:39'), TIMESTAMP('2026-04-12 17:41:04')),
  (1094, 'William', 'Nguyen', 'liam.park@acme.com', '+1-214-809-2698', DATE('2026-04-15'), 'IT_PROG', 239136.04, 0.03, NULL, 84228, 'active', TIMESTAMP('2026-04-19 16:59:04'), TIMESTAMP('2026-04-23 07:54:51')),
  (1095, 'Mary', 'Moore', 'carlos.tanaka@business.io', '+1-762-118-3929', DATE('2026-04-10'), 'AD_VP', 92974.62, 0.19, 2765, 35063, 'suspended', TIMESTAMP('2026-04-17 09:48:33'), TIMESTAMP('2026-04-20 21:27:49')),
  (1096, 'Patricia', 'Thompson', 'charles.anderson@company.com', '+1-580-188-5898', DATE('2026-04-13'), 'SH_CLERK', 39613.66, 0.12, 2681, 67197, 'inactive', TIMESTAMP('2026-04-13 04:34:05'), TIMESTAMP('2026-04-12 13:16:33')),
  (1097, 'James', 'Davis', 'carlos.miller@globaltech.com', '+1-477-494-4365', DATE('2026-04-22'), 'FI_MGR', 61652.87, 0.09, 7209, 47823, 'active', TIMESTAMP('2026-04-13 02:36:13'), TIMESTAMP('2026-04-08 06:49:34')),
  (1098, 'Susan', 'Diallo', 'ravi.brown@enterprise.net', '+1-410-755-5225', DATE('2026-04-15'), 'SA_MAN', 68792.01, 0.17, 6184, 20021, 'pending', TIMESTAMP('2026-04-16 13:08:58'), TIMESTAMP('2026-04-15 04:03:53')),
  (1099, 'Barbara', 'Okafor', 'david.wilson@dataworks.net', '+1-683-334-7824', DATE('2026-04-14'), 'PU_MAN', 169333.44, NULL, 5761, 93468, 'suspended', TIMESTAMP('2026-04-19 14:40:58'), TIMESTAMP('2026-04-23 01:22:00'))
;
