"""
Pipeline config — ticket:_scrum-149
Generated by DEAH Development Pod on 2026-04-21 17:55 UTC

Connection details populated from plan.json (implementation doc + user inputs).
Fill in any remaining FILL_IN values before deploying.
Switch environments by setting the ENV variable:
    ENV=dev  python main.py ...   (default)
    ENV=uat  python main.py ...
    ENV=prod python main.py ...
"""
import os

# ── GCS — sourced from core/utilities/storage/gcs_provider.py env vars ─────────
# These match the defaults used by GCSStorageProvider so bucket config is
# consistent across the whole project.  Override by setting the env vars before
# running any DAG or pipeline script.
GCS_BUCKET_NAME      = os.environ.get("GCS_BUCKET_NAME", "verizon-data-etl-staging")
GCS_PROJECT_ID       = os.environ.get("GCS_PROJECT_ID", "verizon-data")
GCS_CREDENTIALS_PATH = os.environ.get("GCS_CREDENTIALS_PATH", "")

# ── dev ────────────────────────────────────────────────────────────────────────
DEV_PROJECT_ID     = "FILL_IN"
DEV_DATASET_NAME   = "ticket:_scrum-149_dev"
DEV_ENV            = "dev"
DEV_REGION         = "us-central1"
DEV_BQ_LOCATION    = "US"
DEV_RAW_BUCKET     = f"gs://{GCS_BUCKET_NAME}/dev/raw"
DEV_STAGING_BUCKET = f"gs://{GCS_BUCKET_NAME}/dev/staging"
DEV_AUDIT_DATASET  = "audit_dev"
DEV_DB_HOST        = "34.70.79.163"
DEV_DB_PORT        = "3306"
DEV_DB_NAME        = "FILL_IN"
DEV_DB_USER        = "FILL_IN"

# ── uat ────────────────────────────────────────────────────────────────────────
UAT_PROJECT_ID     = "FILL_IN"
UAT_DATASET_NAME   = "ticket:_scrum-149_uat"
UAT_ENV            = "uat"
UAT_REGION         = "us-central1"
UAT_BQ_LOCATION    = "US"
UAT_RAW_BUCKET     = f"gs://{GCS_BUCKET_NAME}/uat/raw"
UAT_STAGING_BUCKET = f"gs://{GCS_BUCKET_NAME}/uat/staging"
UAT_AUDIT_DATASET  = "audit_uat"
UAT_DB_HOST        = "34.70.79.163"
UAT_DB_PORT        = "3306"
UAT_DB_NAME        = "FILL_IN"
UAT_DB_USER        = "FILL_IN"

# ── prod ───────────────────────────────────────────────────────────────────────
PROD_PROJECT_ID     = "FILL_IN"
PROD_DATASET_NAME   = "ticket:_scrum-149_prod"
PROD_ENV            = "prod"
PROD_REGION         = "us-central1"
PROD_BQ_LOCATION    = "US"
PROD_RAW_BUCKET     = f"gs://{GCS_BUCKET_NAME}/prod/raw"
PROD_STAGING_BUCKET = f"gs://{GCS_BUCKET_NAME}/prod/staging"
PROD_AUDIT_DATASET  = "audit_prod"
PROD_DB_HOST        = "34.70.79.163"
PROD_DB_PORT        = "3306"
PROD_DB_NAME        = "FILL_IN"
PROD_DB_USER        = "FILL_IN"

# ── Active config (selected by ENV env variable) ───────────────────────────────
_ENV = os.environ.get("ENV", "dev").lower()

_CONFIGS = {
    "dev": {
        "project_id":          DEV_PROJECT_ID,
        "dataset_name":        DEV_DATASET_NAME,
        "env":                 DEV_ENV,
        "region":              DEV_REGION,
        "bq_location":         DEV_BQ_LOCATION,
        "raw_bucket":          DEV_RAW_BUCKET,
        "staging_bucket":      DEV_STAGING_BUCKET,
        "audit_dataset":       DEV_AUDIT_DATASET,
        "db_host":             DEV_DB_HOST,
        "db_port":             DEV_DB_PORT,
        "db_name":             DEV_DB_NAME,
        "db_user":             DEV_DB_USER,
        "db_password":         os.environ.get("DB_PASSWORD", ""),
        "gcs_bucket_name":     GCS_BUCKET_NAME,
        "gcs_project_id":      GCS_PROJECT_ID,
        "gcs_credentials_path": GCS_CREDENTIALS_PATH,
    },
    "uat": {
        "project_id":          UAT_PROJECT_ID,
        "dataset_name":        UAT_DATASET_NAME,
        "env":                 UAT_ENV,
        "region":              UAT_REGION,
        "bq_location":         UAT_BQ_LOCATION,
        "raw_bucket":          UAT_RAW_BUCKET,
        "staging_bucket":      UAT_STAGING_BUCKET,
        "audit_dataset":       UAT_AUDIT_DATASET,
        "db_host":             UAT_DB_HOST,
        "db_port":             UAT_DB_PORT,
        "db_name":             UAT_DB_NAME,
        "db_user":             UAT_DB_USER,
        "db_password":         os.environ.get("DB_PASSWORD", ""),
        "gcs_bucket_name":     GCS_BUCKET_NAME,
        "gcs_project_id":      GCS_PROJECT_ID,
        "gcs_credentials_path": GCS_CREDENTIALS_PATH,
    },
    "prod": {
        "project_id":          PROD_PROJECT_ID,
        "dataset_name":        PROD_DATASET_NAME,
        "env":                 PROD_ENV,
        "region":              PROD_REGION,
        "bq_location":         PROD_BQ_LOCATION,
        "raw_bucket":          PROD_RAW_BUCKET,
        "staging_bucket":      PROD_STAGING_BUCKET,
        "audit_dataset":       PROD_AUDIT_DATASET,
        "db_host":             PROD_DB_HOST,
        "db_port":             PROD_DB_PORT,
        "db_name":             PROD_DB_NAME,
        "db_user":             PROD_DB_USER,
        "db_password":         os.environ.get("DB_PASSWORD", ""),
        "gcs_bucket_name":     GCS_BUCKET_NAME,
        "gcs_project_id":      GCS_PROJECT_ID,
        "gcs_credentials_path": GCS_CREDENTIALS_PATH,
    },
}

if _ENV not in _CONFIGS:
    raise ValueError(f"Unknown environment \'{_ENV}\'. Set ENV to dev, uat, or prod.")

config = _CONFIGS[_ENV]

# Direct imports — use these in DAGs and scripts
PROJECT_ID            = config["project_id"]
DATASET_NAME          = config["dataset_name"]
ENV                   = config["env"]
REGION                = config["region"]
BQ_LOCATION           = config["bq_location"]
RAW_BUCKET            = config["raw_bucket"]
STAGING_BUCKET        = config["staging_bucket"]
AUDIT_DATASET         = config["audit_dataset"]
DB_HOST               = config["db_host"]
DB_PORT               = config["db_port"]
DB_NAME               = config["db_name"]
DB_USER               = config["db_user"]
DB_PASSWORD           = config["db_password"]
GCS_BUCKET            = config["gcs_bucket_name"]
GCS_PROJECT           = config["gcs_project_id"]
GCS_CREDS_PATH        = config["gcs_credentials_path"]
