package com.prodapt.requirements.model.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * The combined response returned by the Requirements Agent (FastAPI).
 *
 * The agent returns two distinct payloads:
 *   1. {@code jiraTickets}       — list of JIRA tickets ready to be created
 *   2. {@code requirementsDocument} — structured requirements document
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AgentResponse {

    /** Correlation ID echoed back from the agent */
    @JsonProperty("session_id")
    private String sessionId;

    /** Processing status reported by the agent: "success" | "partial" | "error" */
    @JsonProperty("status")
    private String status;

    /** Human-readable message from the agent */
    @JsonProperty("message")
    private String message;

    // ── Response 1: JIRA Tickets ──────────────────────────────────────────────

    /**
     * List of JIRA tickets (epics, stories, sub-tasks, spikes)
     * generated by the Requirements Agent.
     */
    @JsonProperty("jira_tickets")
    private List<JiraTicket> jiraTickets;

    // ── Response 2: Requirements Document ────────────────────────────────────

    /**
     * Structured requirements document extracted / generated
     * from the source file by the Requirements Agent.
     */
    @JsonProperty("requirements_document")
    private RequirementsDocument requirementsDocument;

    /** ISO-8601 timestamp when the agent finished processing */
    @JsonProperty("processed_at")
    private String processedAt;

    /** Duration in milliseconds reported by the agent itself */
    @JsonProperty("agent_duration_ms")
    private Long agentDurationMs;
}
