"""
DE Hub Agent — E-Commerce Pipeline DAG
Cloud Composer / Airflow 2.x

Orchestrates the full data pipeline:
  Source → Staging → Dimensions (SCD-1, SCD-2) → Facts → Aggregates → DQ Checks

Schedule: Daily at 06:00 UTC
"""
from datetime import datetime, timedelta
from pathlib import Path

from airflow import DAG
from airflow.providers.google.cloud.operators.bigquery import (
    BigQueryInsertJobOperator,
    BigQueryCheckOperator,
    BigQueryValueCheckOperator,
)
from airflow.providers.google.cloud.sensors.bigquery import (
    BigQueryTableExistenceSensor,
)
from airflow.operators.dummy import DummyOperator


# ─── Configuration ───────────────────────────────────────────────
# These should come from Airflow Variables in production
PROJECT_ID = "{{ var.value.gcp_project_id }}"
TARGET_DATASET = "{{ var.value.de_hub_target_dataset | default('de_hub_analytics') }}"
SQL_DIR = "{{ var.value.de_hub_sql_dir | default('/home/airflow/gcs/dags/sql/de_hub') }}"

# For local testing / first deploy, you can hardcode:
# PROJECT_ID = "your-project-id"
# TARGET_DATASET = "de_hub_analytics"


# ─── Default Args ────────────────────────────────────────────────
default_args = {
    "owner": "de_hub_agent",
    "depends_on_past": False,
    "email_on_failure": True,
    "email_on_retry": False,
    "email": ["de-hub-alerts@prodapt.com"],
    "retries": 2,
    "retry_delay": timedelta(minutes=5),
    "execution_timeout": timedelta(minutes=30),
}


# ─── DAG Definition ──────────────────────────────────────────────
with DAG(
    dag_id="de_hub_ecommerce_pipeline",
    description="DE Hub Agent — E-Commerce data pipeline: Source → Dim → Fact → Aggregate",
    default_args=default_args,
    schedule_interval="0 6 * * *",  # Daily at 06:00 UTC
    start_date=datetime(2026, 4, 7),
    catchup=False,
    max_active_runs=1,
    tags=["de_hub", "ecommerce", "poc1", "bigquery"],
    doc_md="""
    ## E-Commerce Pipeline (DE Hub Agent POC1)

    **Generated by:** DE_CodeGen_Optimizer_Agent v1.0

    ### Pipeline Flow:
    1. **Staging:** Incremental load of order events
    2. **Dimensions:** SCD-2 for customers, SCD-1 for products, full refresh for shipping regions
    3. **Facts:** Incremental append of orders
    4. **Aggregates:** Full refresh of daily sales summary
    5. **DQ Checks:** Row counts, null checks, referential integrity

    ### Refresh Strategies:
    | Table | Strategy |
    |-------|----------|
    | dim_customer | SCD Type-2 (tracks history) |
    | dim_product | SCD Type-1 (overwrite) |
    | dim_shipping_region | Full refresh |
    | fct_orders | Incremental append |
    | stg_order_events | Incremental append |
    | fct_daily_sales_summary | Full refresh (from fct_orders) |
    """,
) as dag:

    # ─── Start / End markers ─────────────────────────────────────
    start = DummyOperator(task_id="pipeline_start")
    staging_complete = DummyOperator(task_id="staging_complete")
    dims_complete = DummyOperator(task_id="dimensions_complete")
    facts_complete = DummyOperator(task_id="facts_complete")
    end = DummyOperator(task_id="pipeline_end")

    # ─── Staging Layer ───────────────────────────────────────────
    load_stg_order_events = BigQueryInsertJobOperator(
        task_id="load_stg_order_events",
        configuration={
            "query": {
                "query": "{% include 'sql/de_hub/append_stg_order_events.sql' %}",
                "useLegacySql": False,
                "priority": "INTERACTIVE",
            }
        },
        location="us-central1",
    )

    # ─── Dimension Layer ─────────────────────────────────────────
    load_dim_shipping_region = BigQueryInsertJobOperator(
        task_id="load_dim_shipping_region",
        configuration={
            "query": {
                "query": "{% include 'sql/de_hub/refresh_dim_shipping_region.sql' %}",
                "useLegacySql": False,
            }
        },
        location="us-central1",
    )

    load_dim_product = BigQueryInsertJobOperator(
        task_id="load_dim_product",
        configuration={
            "query": {
                "query": "{% include 'sql/de_hub/merge_dim_product.sql' %}",
                "useLegacySql": False,
            }
        },
        location="us-central1",
    )

    load_dim_customer = BigQueryInsertJobOperator(
        task_id="load_dim_customer",
        configuration={
            "query": {
                "query": "{% include 'sql/de_hub/merge_dim_customer.sql' %}",
                "useLegacySql": False,
            }
        },
        location="us-central1",
    )

    # ─── Fact Layer ──────────────────────────────────────────────
    load_fct_orders = BigQueryInsertJobOperator(
        task_id="load_fct_orders",
        configuration={
            "query": {
                "query": "{% include 'sql/de_hub/append_fct_orders.sql' %}",
                "useLegacySql": False,
            }
        },
        location="us-central1",
    )

    # ─── Aggregate Layer ─────────────────────────────────────────
    load_fct_daily_sales = BigQueryInsertJobOperator(
        task_id="load_fct_daily_sales_summary",
        configuration={
            "query": {
                "query": "{% include 'sql/de_hub/refresh_fct_daily_sales_summary.sql' %}",
                "useLegacySql": False,
            }
        },
        location="us-central1",
    )

    # ─── Data Quality Checks ─────────────────────────────────────
    dq_dim_customer_not_empty = BigQueryValueCheckOperator(
        task_id="dq_dim_customer_not_empty",
        sql=f"SELECT COUNT(*) FROM `{TARGET_DATASET}.dim_customer` WHERE _is_current = TRUE",
        pass_value=1,
        use_legacy_sql=False,
        tolerance=0,
    )

    dq_fct_orders_not_empty = BigQueryValueCheckOperator(
        task_id="dq_fct_orders_not_empty",
        sql=f"SELECT COUNT(*) FROM `{TARGET_DATASET}.fct_orders`",
        pass_value=1,
        use_legacy_sql=False,
        tolerance=0,
    )

    dq_orders_have_valid_customers = BigQueryCheckOperator(
        task_id="dq_orders_have_valid_customers",
        sql=f"""
            SELECT COUNT(*) = 0
            FROM `{TARGET_DATASET}.fct_orders` o
            LEFT JOIN `{TARGET_DATASET}.dim_customer` c
              ON o.customer_id = c.customer_id AND c._is_current = TRUE
            WHERE c.customer_id IS NULL
        """,
        use_legacy_sql=False,
    )

    dq_orders_have_valid_products = BigQueryCheckOperator(
        task_id="dq_orders_have_valid_products",
        sql=f"""
            SELECT COUNT(*) = 0
            FROM `{TARGET_DATASET}.fct_orders` o
            LEFT JOIN `{TARGET_DATASET}.dim_product` p
              ON o.product_id = p.product_id
            WHERE p.product_id IS NULL
        """,
        use_legacy_sql=False,
    )

    dq_no_null_pks = BigQueryCheckOperator(
        task_id="dq_no_null_primary_keys",
        sql=f"""
            SELECT
              (SELECT COUNT(*) FROM `{TARGET_DATASET}.dim_customer` WHERE customer_id IS NULL) +
              (SELECT COUNT(*) FROM `{TARGET_DATASET}.dim_product` WHERE product_id IS NULL) +
              (SELECT COUNT(*) FROM `{TARGET_DATASET}.fct_orders` WHERE order_id IS NULL)
              = 0
        """,
        use_legacy_sql=False,
    )

    dq_daily_sales_matches_orders = BigQueryCheckOperator(
        task_id="dq_daily_sales_reconciliation",
        sql=f"""
            WITH order_totals AS (
              SELECT COUNT(*) AS order_count FROM `{TARGET_DATASET}.fct_orders`
            ),
            summary_totals AS (
              SELECT SUM(total_orders) AS summary_count FROM `{TARGET_DATASET}.fct_daily_sales_summary`
            )
            SELECT ABS(order_totals.order_count - summary_totals.summary_count) <= order_totals.order_count * 0.05
            FROM order_totals, summary_totals
        """,
        use_legacy_sql=False,
    )

    # ─── Task Dependencies ───────────────────────────────────────
    # Pipeline flow:
    #   start → staging → dims → facts → aggregates → DQ → end
    #
    #   staging:   stg_order_events (parallel possible)
    #   dims:      shipping_region, product, customer (parallel — no interdependence)
    #   facts:     fct_orders (depends on dims for FK validation)
    #   aggregate: daily_sales (depends on fct_orders)
    #   DQ:        all checks after aggregate

    start >> load_stg_order_events >> staging_complete

    staging_complete >> [load_dim_shipping_region, load_dim_product, load_dim_customer]
    [load_dim_shipping_region, load_dim_product, load_dim_customer] >> dims_complete

    dims_complete >> load_fct_orders >> facts_complete

    facts_complete >> load_fct_daily_sales >> [
        dq_dim_customer_not_empty,
        dq_fct_orders_not_empty,
        dq_orders_have_valid_customers,
        dq_orders_have_valid_products,
        dq_no_null_pks,
        dq_daily_sales_matches_orders,
    ] >> end
